FROM mcr.microsoft.com/playwright:v1.51.1-noble

WORKDIR /app
ENV NEXT_TELEMETRY_DISABLED=1
ENV CI=true

COPY package*.json ./
COPY prisma ./prisma
RUN npm ci

COPY . .
RUN npx prisma generate

CMD ["npm", "run", "qa:e2e"]
